# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
  repositories:
  - repository: IICS-CDP-CICD-demo # The name used to reference this repository in the checkout step
    type: github
    endpoint: brandon-bird-inf
    name: tjohnsoninformatica/IICS-CDP-CICD-demo
    ref: UAT
    trigger: 
      - Dev

trigger: none

pool:
  name: devops-local-pool

variables:
- name: COMMIT_HASH
  value: 1fcd233fd8eae05e47d4cd824bce3b145d2f4f3f
- name: IICS_LOGIN_URL
  value: https://dm-us.informaticacloud.com
- name: IICS_POD_URL
  value: https://na1.dm-us.informaticacloud.com/saas
- group: lib_psdekeyvault

stages:
  - stage: Review_deployment
    jobs: 
    - job: Run_Test
      steps:
        - task: CmdLine@2
          name: install_requirements
          inputs:
            script:
              python3 -m pip install --upgrade pip
              pip install -r requirements.txt
        
        - task: CmdLine@2
          name: get_objects_and_test
          inputs:
            script: python ./scripts/infa_get_updates.py
          env:
            ### Handle lack of "_" in KV variables
            IICS_USERNAME: $(IICS-USERNAME)
            IICS_PASSWORD: $(IICS-PASSWORD)

  - stage: Deploy_UAT
    jobs:
    - job: commit_uat
      steps:
        - checkout: IICS-CDP-CICD-demo
    
        - task: CmdLine@2
          name: cherry_pick_commit
          inputs:
            script: cd ./IICS-CDP-CICD-demo; git fetch --all; git cherry-pick --strategy=recursive -X theirs ${COMMIT_HASH}; git push