# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  name: devops-local-pool

variables:
- name: COMMIT_HASH
  value: 1fcd233fd8eae05e47d4cd824bce3b145d2f4f3f
- name: IICS_LOGIN_URL
  value: https://dm-us.informaticacloud.com
- name: IICS_POD_URL
  value: https://na1.dm-us.informaticacloud.com/saas
- group: lib_psdekeyvault

stages:
  - stage: Review_deployment
    ### Handle lack of "_" in KV variables
    variables:
      - name: IICS_USERNAME
        value: ${{ env.IICS-USERNAME }}
      - name: IICS_PASSWORD
        value: ${{ IICS-PASSWORD }}
      - name: UAT_IICS_USERNAME
        value: ${{ UAT-IICS-USERNAME }}
      - name: UAT_IICS_PASSWORD
        value: ${{ UAT-IICS-PASSWORD }}
    jobs: 
    - job: Run_Test
      steps:
        - task: CmdLine@2
          name: install_requirements
          inputs:
            script:
              python3 -m pip install --upgrade pip
              pip install -r requirements.txt
        
        - task: CmdLine@2
          name: get_objects_and_test
          inputs:
            script: python ./scripts/infa_get_updates.py