# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
  repositories:
  - repository: IICS-CDP-CICD-demo # The name used to reference this repository in the checkout step
    type: github
    endpoint: bb-github-pat
    name: tjohnsoninformatica/IICS-CDP-CICD-demo

trigger: none

pool:
  name: devops-local-pool

variables:
- name: COMMIT_HASH
  value: 9f5311ebe6440d765bdc2b1537e0025cbcb9f4da
- name: IICS_LOGIN_URL
  value: https://dm-us.informaticacloud.com
- name: IICS_POD_URL
  value: https://na1.dm-us.informaticacloud.com/saas
- group: lib_psdekeyvault

stages:
  - stage: Review_deployment
    jobs: 
    - job: Run_Test
      steps:
        - task: CmdLine@2
          name: install_requirements
          inputs:
            script:
              python3 -m pip install --upgrade pip
              pip install -r requirements.txt
        
        - task: CmdLine@2
          name: get_objects_and_test
          inputs:
            script: python ./scripts/infa_get_updates.py
          env:
            ### Handle lack of "_" in KV variables
            IICS_USERNAME: $(IICS-USERNAME)
            IICS_PASSWORD: $(IICS-PASSWORD)

  - stage: Deploy_UAT
    jobs:
    - job: commit_uat
      steps:
        - checkout: self
        - checkout: IICS-CDP-CICD-demo
          persistCredentials: "true"

        - task: CmdLine@2
          name: cherry_pick_commit
          inputs:
            script: cd ./IICS-CDP-CICD-demo; git switch UAT; git fetch --all; git cherry-pick --strategy=recursive -X theirs ${COMMIT_HASH}; git push

        - task: CmdLine@2
          name: get_latest_commit
          inputs:
            script: cd ./IICS-CDP-CICD-demo; git pull; export UAT_COMMIT_HASH=$(git log -1 --pretty=format:%H)
      
        - task: CmdLine@2
          name: sync_and_test_uat
          inputs:
            script: python ./iics-promotion-pipeline/scripts/infa_update_and_test.py
          env:
            ### Handle lack of "_" in KV variables
            UAT_IICS_USERNAME: $(UAT-IICS-USERNAME)
            UAT_IICS_PASSWORD: $(UAT-IICS-PASSWORD)
            UAT_COMMIT_HASH: ${UAT_COMMIT_HASH}