# This sample source code is offered only as an example of what can or might be built using the IICS Github APIs, 
# and is provided for educational purposes only. This source code is provided "as-is" 
# and without representations or warrantees of any kind, is not supported by Informatica.
# Users of this sample code in whole or in part or any extraction or derivative of it 
# assume all the risks attendant thereto, and Informatica disclaims any/all liabilities 
# arising from any such use to the fullest extent permitted by law.

resources:
  repositories:
  - repository: IICS-CDP-CICD-demo # The name used to reference this repository in the checkout step
    type: github
    endpoint: bb-github-pat
    name: tjohnsoninformatica/IICS-CDP-CICD-demo

trigger: none

pool:
  name: devops-local-pool

parameters:
  - name: COMMIT_HASH
    type: string

variables:
- name: COMMIT_HASH
  value: ${{ parameters.COMMIT_HASH }}
- name: IICS_LOGIN_URL
  value: https://dm-us.informaticacloud.com
- name: IICS_POD_URL
  value: https://na1.dm-us.informaticacloud.com/saas
- group: lib_psdekeyvault

stages:
  - stage: Review_deployment
    jobs: 
    - job: Run_Test
      steps:
        - task: CmdLine@2
          name: install_requirements
          inputs:
            script:
              python3 -m pip install --upgrade pip
              pip install -r requirements.txt
            failOnStderr: true
        
        - task: CmdLine@2
          name: get_objects_and_test
          inputs:
            script: python3 ./scripts/infa_get_updates.py
            failOnStderr: true
          env:
            ### Handle lack of "_" in KV variables
            IICS_USERNAME: $(IICS-USERNAME)
            IICS_PASSWORD: $(IICS-PASSWORD)

  - stage: Deploy_UAT
    jobs:
    - job: commit_uat
      steps:
        - checkout: self
        - checkout: IICS-CDP-CICD-demo
          persistCredentials: "true"

        - task: CmdLine@2
          name: cherry_pick_commit
          inputs:
            script: cd ./IICS-CDP-CICD-demo; git switch UAT; git cherry-pick --strategy=recursive -X theirs ${COMMIT_HASH}; git push

        - task: CmdLine@2
          name: get_latest_commit
          inputs:
            script: cd ./IICS-CDP-CICD-demo; git pull; echo "##vso[task.setvariable variable=UAT_COMMIT_HASH]$(git log -1 --pretty=format:%H)"
            failOnStderr: true
      
        - task: CmdLine@2
          name: sync_and_test_uat
          inputs:
            script: python3 ./iics-promotion-pipeline/scripts/infa_update_and_test.py
          env:
            ### Handle lack of "_" in KV variables
            UAT_IICS_USERNAME: $(UAT-IICS-USERNAME)
            UAT_IICS_PASSWORD: $(UAT-IICS-PASSWORD)
            UAT_COMMIT_HASH: $(UAT_COMMIT_HASH)