# This sample source code is offered only as an example of what can or might be built using the IICS Github APIs, 
# and is provided for educational purposes only. This source code is provided "as-is" 
# and without representations or warrantees of any kind, is not supported by Informatica.
# Users of this sample code in whole or in part or any extraction or derivative of it 
# assume all the risks attendant thereto, and Informatica disclaims any/all liabilities 
# arising from any such use to the fullest extent permitted by law.

parameters:
  - name: PROJECT_NAME
    type: string
  - name: MAPPING_NAME
    type: string

variables:
- name: PROJECT_NAME
  value: ${{ parameters.PROJECT_NAME}}
- name: MAPPING_NAME
  value: ${{ parameters.MAPPING_NAME }}
- name: IICS_LOGIN_URL
  value: https://dm-us.informaticacloud.com
- name: IICS_POD_URL
  value: https://na1.dm-us.informaticacloud.com/saas
- group: lib_psdekeyvault

trigger: none

pool:
  name: devops-local-pool

jobs: 
  - job: backout_code
    displayName: Backout ${{ parameters.MAPPING_NAME }} in ${{ parameters.PROJECT_NAME }}
    steps:
      - task: CmdLine@2
        name: install_requirements
        inputs:
          script:
            python -m pip install --upgrade pip
            pip install -r requirements.txt
          failOnStderr: true
        
      - task: CmdLine@2
        name: get_objects_and_test
        inputs:
          script: python ./scripts/rollback_mapping.py
          failOnStderr: true
        env:
          ### Handle lack of "_" in KV variables
          IICS_USERNAME: $(IICS-USERNAME)
          IICS_PASSWORD: $(IICS-PASSWORD)