# This sample source code is offered only as an example of what can or might be built using the IICS Github APIs, 
# and is provided for educational purposes only. This source code is provided "as-is" 
# and without representations or warrantees of any kind, is not supported by Informatica.
# Users of this sample code in whole or in part or any extraction or derivative of it 
# assume all the risks attendant thereto, and Informatica disclaims any/all liabilities 
# arising from any such use to the fullest extent permitted by law.

parameters:
  - name: PATH_NAME
    type: string
  - name: OBJECT_NAME
    type: string

variables:
- name: PATH_NAME
  value: ${{ parameters.PATH_NAME}}
- name: OBJECT_NAME
  value: ${{ parameters.OBJECT_NAME }}
- name: IICS_LOGIN_URL
  value: https://dm-us.informaticacloud.com
- name: IICS_POD_URL
  value: https://na1.dm-us.informaticacloud.com/saas
- group: lib_psdekeyvault

trigger: none

pool:
  name: devops-local-pool

jobs: 
  - job: backout_code
    displayName: Backout ${{ parameters.OBJECT_NAME }} in ${{ parameters.PATH_NAME }}
    steps:
      - task: CmdLine@2
        name: install_requirements
        inputs:
          script:
            python3 -m pip install --upgrade pip
            pip install -r requirements.txt
          failOnStderr: true
        
      - task: CmdLine@2
        name: rollback_object
        inputs:
          script: python3 ./scripts/rollback_mapping.py
          failOnStderr: true
        env:
          ### Send variables to the environment. Notice KV only uses "-" which makes python choke
          UAT_IICS_USERNAME: $(UAT-IICS-USERNAME)
          UAT_IICS_PASSWORD: $(UAT-IICS-PASSWORD)
          PATH_NAME: $(PATH_NAME)
          OBJECT_NAME: $(OBJECT_NAME)

          