


resources:
  repositories:
  - repository: IICS-CDP-CICD-demo # The name used to reference this repository in the checkout step
    type: github
    endpoint: bb-github-pat
    name: tjohnsoninformatica/IICS-CDP-CICD-demo

trigger: none

pool:
  name: devops-local-pool

parameters:
  - name: COMMIT_HASH
    type: string

variables:
- name: COMMIT_HASH
  value: ${{ parameters.COMMIT_HASH }}

stages:
  - template: idmc-deployment.yml  # Template reference
    parameters:
      commit_hash: $(COMMIT_HASH)
      source_env: DEV
      target_env: UAT
      team_kv: lib_psdekeyvault
      external_repo: tjohnsoninformatica/IICS-CDP-CICD-demo