# This sample source code is offered only as an example of what can or might be built using the IICS Github APIs, 
# and is provided for educational purposes only. This source code is provided "as-is" 
# and without representations or warrantees of any kind, is not supported by Informatica.
# Users of this sample code in whole or in part or any extraction or derivative of it 
# assume all the risks attendant thereto, and Informatica disclaims any/all liabilities 
# arising from any such use to the fullest extent permitted by law.

resources:
  repositories:
  - repository: IICS-CDP-CICD-demo # The name used to reference this repository in the checkout step
    type: github
    endpoint: bb-github-pat
    name: tjohnsoninformatica/IICS-CDP-CICD-demo

trigger: none

parameters:
  - name: COMMIT_HASH
    type: string

stages:
  - template: idmc-deployment.yml  # Template reference
    parameters:
      commit_hash: ${{ parameters.COMMIT_HASH }}
      source_env: DEV
      target_env: UAT
      team_kv: lib_psdekeyvault
      external_repo: IICS-CDP-CICD-demo