# This sample source code is offered only as an example of what can or might be built using the IICS Github APIs, 
# and is provided for educational purposes only. This source code is provided "as-is" 
# and without representations or warrantees of any kind, is not supported by Informatica.
# Users of this sample code in whole or in part or any extraction or derivative of it 
# assume all the risks attendant thereto, and Informatica disclaims any/all liabilities 
# arising from any such use to the fullest extent permitted by law.

parameters:
  - name: commit_hash
    type: string
  - name: source_env
    type: string
  - name: target_env
    type: string
  - name: team_kv
    type: string
  - name: external_repo
    type: string
    default: ""

stages:
  - stage: Review_deployment
    variables:
      - group: ${{ parameters.team_kv }}
      - name: source_login
        value: $(${{ parameters.source_env }}-IICS-USERNAME)
      - name: source_password
        value: ${{ parameters.source_env }}-IICS-PASSWORD
      - name: IICS_LOGIN_URL
        value: https://dm-us.informaticacloud.com
      - name: IICS_POD_URL
        value: https://na1.dm-us.informaticacloud.com/saas
    jobs: 
    - job: Run_Test
      steps:
        - task: CmdLine@2
          name: install_requirements
          inputs:
            script:
              python3 -m pip install --upgrade pip
              pip install -r requirements.txt
            failOnStderr: true
        
        - task: bash@3
          inputs:
            targetType: inline
            script: echo $IICS_USERNAME
          env: 
            IICS_USERNAME: $(source_login)        

        
        - task: CmdLine@2
          name: get_objects_and_test
          inputs:
            script: python ./scripts/infa_get_updates.py
            failOnStderr: true
          env:
            ### Handle lack of "_" in KV variables
            IICS_USERNAME: $($(source_login))
            IICS_PASSWORD: $($(source_password))