jobs:
  login:
    name: Set IICS Session Secrets
    environment:
      name: development
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      IICS_LOGIN_URL: https://dm-us.informaticacloud.com
      IICS_USERNAME: ${{ secrets.IICS_USERNAME }}
      IICS_PASSWORD: ${{ secrets.IICS_PASSWORD }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Install python and dependent modules
      - uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      
      - name: Install python modules
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

      # Runs a single command using the runners shell
      - name: Login to development
        run: python ./scripts/infa_login.py